### ISSUE TITLE
NullPointerException when specifying vias

### ISSUE THREAD

**Issue by cor-mt** [freerouting/freerouting#101]
With my first test to auto-route a double sided pcb exported from pcb-rnd I discovered it's only trying routes on the same layer of the pcb that will never work because there is smd components on both sides. So I took the .rules file in the tests folder and adapted it to look kind-of workable for my situation. But it always fail with a NullPointerException and afterwards nothing happens.

Versions: Tested with V1.4.5.1 and V1.5.0
Platforms: Linux and later inside NetBeans on M$ with OpenJDK11.

The test rules (github removes the newlines and indentation here in a code section??):
`
(rules PCB test
  (snap_angle
    fortyfive_degree
  )
  (autoroute_settings
    (fanout off)
    (autoroute on)
    (postroute on)
    (vias on)
    (via_costs 50)
    (plane_via_costs 5)
    (start_ripup_costs 100)
    (start_pass_no 1510)
    (layer_rule 3__top_copper
      (active on)
      (preferred_direction vertical)
      (preferred_direction_trace_costs 1.0)
      (against_preferred_direction_trace_costs 2.0)
    )
    (layer_rule 7__bottom_copper
      (active on)
      (preferred_direction horizontal)
      (preferred_direction_trace_costs 1.0)
      (against_preferred_direction_trace_costs 2.0)
    )
  )
	(rule
		(width 0.3)
		(clear 0.2)
	)
	(padstack pstk_1
						(shape (circle 3__top_copper 2.2 0.0 0.0))
  					(shape (circle 7__bottom_copper 2.2 0.0 0.0))
  					(attach off)
	)
	(via pstk_1 pstk_1 default)
	(via_rule default pstk_1)
	(class default
				 (clearance_class default)
				 (via_rule default)
				 (rule (width 0.3))
				 (circuit (use_layer 3__top_copper 7__bottom_copper))
	)
)
`

The error log:
`java.lang.NullPointerException: null
	at app.freerouting.library.BoardLibrary.add_via_padstack(BoardLibrary.java:101) ~[main/:?]
	at app.freerouting.designforms.specctra.Network.read_via_info(Network.java:560) ~[main/:?]
	at app.freerouting.designforms.specctra.RulesFile.read_via_info(RulesFile.java:262) ~[main/:?]
	at app.freerouting.designforms.specctra.RulesFile.read(RulesFile.java:120) ~[main/:?]
	at app.freerouting.gui.DesignFile.read_rules_file(DesignFile.java:262) ~[main/:?]
	at app.freerouting.gui.MainApplication.create_board_frame(MainApplication.java:386) ~[main/:?]
	at app.freerouting.gui.MainApplication.open_board_design_action(MainApplication.java:305) ~[main/:?]
	at app.freerouting.gui.MainApplication.lambda$new$2(MainApplication.java:250) ~[main/:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6635) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6400) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2263) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]`

The "via_padstacks" is declared at BoardLibrary.java:181 as null and could be initialized by line 16 but NetBeands didn't find any usages for that function. This is my first time opening a java project in a debugger but shouldn't the "via_padstacks" be initialised as an empty list istead of null, or are my rules buggered?

**Comment by andrasfuchs** [comment]
@cor-mt Could you give me the DSN+.rules files to work with? We have a new version, but I can't tell if it fixes your problem.

You can also try it by downloading the snapshot build from here: 
https://github.com/freerouting/freerouting/releases/tag/SNAPSHOT
