### ISSUE TITLE
I believe newer DSN files don't work

### ISSUE THREAD

**Issue by nmz787** [freerouting/freerouting#6]
When using the binary I see the message "unable to read .dsl-file" in first open dialog GUI.
This is the file:
http://diyhpl.us/~nmz787/LPC18XX_43XX_SCH.DSN

When I tried it in NetBeans, I got this:
java.lang.Error: Illegal character <�>
    at designformats.specctra.SpecctraFileScanner.next_token(SpecctraFileScanner.java:1407)
    at designformats.specctra.DsnFile.read(DsnFile.java:59)
    at interactive.BoardHandling.import_design(BoardHandling.java:1045)
    at gui.BoardFrame.read(BoardFrame.java:180)
    at gui.MainApplication.create_board_frame(MainApplication.java:301)
    at gui.MainApplication.open_board_design_action(MainApplication.java:236)
    at gui.MainApplication.access$200(MainApplication.java:31)
    at gui.MainApplication$4.actionPerformed(MainApplication.java:171)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2739)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:719)
    at java.awt.EventQueue$4.run(EventQueue.java:717)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by bobc** [comment]
Specctra DSN is an ASCII file format. That file might have a DSN suffix but I don't think it is anything to do with Specctra DSN.

To avoid confusion, freerouter could check that the DSN file starts with "(pcb".

**Comment by SergeySSmirnov** [comment]
Me too have this problem.
In my case Exception generates Illegal character <M>.
*.dsn file is correct, starts with (pcb. 
Can you help?

**Comment by bobc** [comment]
@SergeySSmirno if you post the file somewhere, I could have a look.

**Comment by SergeySSmirnov** [comment]
Yes of course: https://www.dropbox.com/s/1wu8f4uysfz4hti/%D0%9F%D0%B0%D1%8F%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D1%81%D1%82%D0%B0%D0%BD%D1%86%D0%B8%D1%8F.dsn?dl=0

**Comment by alejodeiuliis** [comment]
Having the same issue, when trying to exec .jar file and load my .dsn file (in Linux Mint 19.1):

java.lang.Error: Illegal character <->
	at freert.spectra.DsnFileScanner.next_token(DsnFileScanner.java:1744)
	at freert.spectra.DsnKeywordNetwork.read_net_pins(DsnKeywordNetwork.java:517)
	at freert.spectra.DsnKeywordNetwork.read_net_scope(DsnKeywordNetwork.java:377)
	at freert.spectra.DsnKeywordNetwork.read_scope(DsnKeywordNetwork.java:94)
	at freert.spectra.DsnKeywordScope.read_scope(DsnKeywordScope.java:112)
	at freert.spectra.DsnReadFile.read(DsnReadFile.java:81)
	at interactive.IteraBoard.import_design(IteraBoard.java:1084)
	at gui.BoardFrame.import_design(BoardFrame.java:303)
	at freert.main.MainApplication.open_board_file(MainApplication.java:212)
	at freert.main.MainApplication.access$0(MainApplication.java:199)
	at freert.main.MainApplication$ImportDesign.doInBackground(MainApplication.java:258)
	at freert.main.MainApplication$ImportDesign.doInBackground(MainApplication.java:1)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by andrasfuchs** [comment]
@alejodeiuliis Could you send us the DSN file?

I'm working on [the currently active fork](https://github.com/miho/freerouting) of this project, and I could test your file, and fix the issue if I can.

**Comment by andrasfuchs** [comment]
@SergeySSmirnov Your file contained cyrillic letters, that caused the problem.

@alejodeiuliis I updated the source today, so the error message you are going to get will show you the exact position in the file where the problem is. 
For more details check out this related issue: https://github.com/miho/freerouting/issues/11

**Comment by nmz787** [comment]
Any error message with the file I posted?

**Comment by andrasfuchs** [comment]
Yes, that file is a binary file. Freerouting supports only the text-based Specctra DSN file format at the moment.

**Comment by nmz787** [comment]
Well I did get the non-ASCII file from a Cadence tool saving as Specctra
format. Should I open a separate ticket for non-ASCII file support request?

**Comment by andrasfuchs** [comment]
Yes, please!
